#!/bin/bash

set -o errexit

tmpDir=/tmp/buildSS

mkdir -p $tmpDir
rm -rf $tmpDir/*

cp Dockerfile $tmpDir/
cp ShapeShifter/RunTests.sh $tmpDir/
cp ShapeShifter/RunTests2.sh $tmpDir/
cp VERSION $tmpDir/
mkdir $tmpDir/Tests/
cp -r ShapeShifter/Tests/InputData $tmpDir/Tests/
cp -r ShapeShifter/Tests/OutputData $tmpDir/Tests/
cp ShapeShifter/*.py $tmpDir
cd $tmpDir

docker build -t srp33/shapeshifter:version$(cat VERSION) .

docker run -i --rm srp33/shapeshifter:version$(cat VERSION) /RunTests2.sh
#docker run -i --rm srp33/shapeshifter:version$(cat VERSION) /bin/bash

cd -
rm -rf $tmpDir/

