#!/bin/bash

set -o errexit

tmpDir=/tmp/buildSS

mkdir -p $tmpDir
rm -rf $tmpDir/*

cp Dockerfile $tmpDir/
cp Tests/RunTests.sh $tmpDir/
cp Tests/RunTests2.sh $tmpDir/
cp VERSION $tmpDir/
cp MANIFEST.in $tmpDir/
cp README.md $tmpDir/
mkdir $tmpDir/Tests/
cp -r Tests/InputData $tmpDir/Tests/
cp -r Tests/OutputData $tmpDir/Tests/
cp Tests/*.py $tmpDir/
cp -r shapeshifter $tmpDir
cp setup.py $tmpDir
cd $tmpDir
docker build -t srp33/shapeshifter:version$(cat VERSION) .

docker run -i --rm srp33/shapeshifter:version$(cat VERSION) /RunTests2.sh
#docker run -i --rm srp33/shapeshifter:version$(cat VERSION) /bin/bash

cd -
rm -rf $tmpDir/

