from shapeshifter.files.ssfile import SSFile
from shapeshifter.files.arffile import ARFFFile
from shapeshifter.files.csvfile import CSVFile
from shapeshifter.files.excelfile import ExcelFile
from shapeshifter.files.gctfile import GCTFile
from shapeshifter.files.hdf5file import HDF5File
from shapeshifter.files.htmlfile import HTMLFile
from shapeshifter.files.jsonfile import JSONFile
from shapeshifter.files.jupyternotebookfile import JupyterNBFile
from shapeshifter.files.kallisto_est_counts_file import KallistoEstCountsFile
from shapeshifter.files.kallisto_tpm_file import KallistoTPMFile
from shapeshifter.files.msgpackfile import MsgPackFile
from shapeshifter.files.parquetfile import ParquetFile
from shapeshifter.files.picklefile import PickleFile
from shapeshifter.files.rmarkdownfile import RMarkdownFile
from shapeshifter.files.salmon_num_reads_file import SalmonNumReadsFile
from shapeshifter.files.salmon_tpm_file import SalmonTPMFile
from shapeshifter.files.sqlitefile import SQLiteFile
from shapeshifter.files.statafile import StataFile
from shapeshifter.files.tsvfile import TSVFile