#!/bin/bash

tmpDir=/tmp/buildSS

mkdir -p $tmpDir
rm -rf $tmpDir/*

cp Dockerfile $tmpDir/
cp RunTests.sh $tmpDir/
cp VERSION $tmpDir/
mkdir $tmpDir/Tests/
cp -r Tests/InputData $tmpDir/Tests/
cp -r Tests/OutputData $tmpDir/Tests/
cp *.py $tmpDir
cd $tmpDir

docker build -t srp33/shapeshifter:version$(cat VERSION) .

docker run -i --rm srp33/shapeshifter:version$(cat VERSION) /RunTests.sh
#docker run -i --rm srp33/shapeshifter:version$(cat VERSION) /bin/bash

cd -
rm -rf $tmpDir/

